
GET http://127.0.0.1:8000/products/ HTTP/1.1

###

GET http://127.0.0.1:8000/products/1 HTTP/1.1

###

PUT  http://127.0.0.1:8000/products/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyNTUwNTMyLCJpYXQiOjE3NDI1NTAyMzIsImp0aSI6ImMxNmExNmJlNTRlMTQ3ZjJhZjkxN2ZlNjk5MmI5NTc2IiwidXNlcl9pZCI6M30.KR61xvD4NZ_TVi7rGJaKPpuYy_yWoSv2uYIvjDHOoSk

{
    "name" : "new test",
    "descriptions" : "test product from rest client with jwt" ,
    "price" : 99 ,
    "stock" : 4
}

###

DELETE  http://127.0.0.1:8000/products/10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyNTY4MDIwLCJpYXQiOjE3NDI1Njc3MjAsImp0aSI6Ijk1N2VlYzI5OTEyYTQzZTY4ZDY5ZGE1MTU5ZDkzOTE5IiwidXNlcl9pZCI6MX0.-s4bLIOU5g2xtwemmbIUWZ9DRylqRqWtgd_2V3qK07k

###

POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyNTUwNTMyLCJpYXQiOjE3NDI1NTAyMzIsImp0aSI6ImMxNmExNmJlNTRlMTQ3ZjJhZjkxN2ZlNjk5MmI5NTc2IiwidXNlcl9pZCI6M30.KR61xvD4NZ_TVi7rGJaKPpuYy_yWoSv2uYIvjDHOoSk

{
    "name" : "test2",
    "descriptions" : "test product from rest client with jwt" ,
    "price" : 99 ,
    "stock" : 4
}

###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username" : "mohy",
    "password" : "123" 
    
}

###

POST http://127.0.0.1:8000/api/token/refresh HTTP/1.1
Content-Type: application/json

{
    "refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0MjYzNzc0NiwiaWF0IjoxNzQyNTUxMzQ2LCJqdGkiOiIxNDhkY2I2NGRjOTc0ZDA3ODg5MmUwMmZmYzA2MTU1ZSIsInVzZXJfaWQiOjN9.5NA_hwhSBd5STi4JQkPq67Xlc8dM5-EdNHkek4ps-Ds"
}

###

GET http://127.0.0.1:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyNzM4MjI2LCJpYXQiOjE3NDI3Mzc5MjYsImp0aSI6IjZkOGQ0MzM1YmMyZTQ4NWI4ZjdmZjY1YjczNGZiZDVhIiwidXNlcl9pZCI6MX0.EE0HYkoeeQi5Pfy4LYJrlwLdKXikUxaT0yJf3umg5C4

###

GET  http://127.0.0.1:8000/orders/a5bb0a76-a794-4ef8-b650-0fde934d2d67 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyNzM4NDY3LCJpYXQiOjE3NDI3MzgxNjcsImp0aSI6ImE4ZWExZTczYWU2ODQ1Yjg4MThiZmJmZWZhNDcwMjA0IiwidXNlcl9pZCI6MX0.skMmwQr5sihmccAZKw_SLa3tRCNIaF06YRDkTj6rjg4

###
POST http://127.0.0.1:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyNzM4NTkzLCJpYXQiOjE3NDI3MzgyOTMsImp0aSI6IjJkMWM3OGNkMTFiZTQ3ZjE4MjQ3YzMyNjBlODQwMjVkIiwidXNlcl9pZCI6MX0.LERvcw_j4b6AqosiWflrbahGD1Cw1hEFhq85g2R1X_M

{
      "status": "Pending",
      "items": [
        {
          "product": 3,
          "quantity": 3
        }
      ]
}

###

PUT http://127.0.0.1:8000/orders/a5bb0a76-a794-4ef8-b650-0fde934d2d67/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyNzM4OTUzLCJpYXQiOjE3NDI3Mzg2NTMsImp0aSI6IjY4YjY1N2RmMjA3YjQ4YjI5MjJmMTNiODM3NTQ2MzA2IiwidXNlcl9pZCI6MX0.SMcohUW-Nh0Y4u7jE9AmsirKx6KcKOVM0AZde5MWKGU

{
      "status": "Confirmed",
      "items": [
        {
          "product": 3,
          "quantity": 3
        }
      ]
    }